#pragma once

struct _LDR_DATA_TABLE_ENTRY;
using LDR_DATA_TABLE_ENTRY = _LDR_DATA_TABLE_ENTRY;

struct _IMAGE_SECTION_HEADER;
using IMAGE_SECTION_HEADER = _IMAGE_SECTION_HEADER;

struct _IMAGE_DOS_HEADER;
using IMAGE_DOS_HEADER = _IMAGE_DOS_HEADER;

#ifdef _WIN64
struct _IMAGE_NT_HEADERS64;
using IMAGE_NT_HEADERS = _IMAGE_NT_HEADERS;
#else
struct _IMAGE_NT_HEADERS;
using IMAGE_NT_HEADERS = _IMAGE_NT_HEADERS;
#endif
